
steps:

  - id: "Fetch Secrets"
    waitFor: []
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo $(gcloud secrets versions access latest --secret=rubygems-api-key) > rubygems-api-key.txt'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run Tests'
    args:
      - 'build'
      - '.'
      - '-f'
      - 'RunTestsDockerfile'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Publish Gem'
    entrypoint: 'bash'
    waitFor:
      - 'Run Tests'
    args:
      - '-c'
      - 'docker build . -f PublishGemDockerfile
      --build-arg RUBYGEMS_API_KEY=$(cat rubygems-api-key.txt)
      '