
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
      - '-t'
      - 'RunTestsDockerfile'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
      - '-t'
      - 'PublishGemDockerfile'
