
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
      - '-f'
      - 'RunTestsDockerfile'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
      - '-f'
      - 'PublishGemDockerfile'
      - '--build-arg'
      - 'RUBYGEMS_API_KEY=${_RUBYGEMS_API_KEY}'