apiVersion: v1
kind: ConfigMap
metadata:
  name: unwanted
annotations:
  source: resources.yaml
data:
  foo: bar

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wanted
annotations:
  source: resources.yaml
data:
  foo: baz