require_relative './app'
require_relative './gen'
require_relative './val_man'
require_relative './base_helper'
require_relative './../templates/res_template'
require_relative './../templates/service'
require_relative './../templates/deployment'